#include "Input.hpp"

namespace iv
{

const StringIO< Input::Type >::ValuesType StringIO< Input::Type >::Values = 
{
    { Input::Type::Press, "Press" },
    { Input::Type::Release, "Release" },
    { Input::Type::Trigger, "Trigger" }
};

const StringIO< Input::Key >::ValuesType StringIO< Input::Key >::Values = 
{
    { Input::Key::None, "None" },
    { Input::Key::Character, "Character" },
    { Input::Key::Space, "Space" },
    { Input::Key::Apostrophe, "Apostrophe" },
    { Input::Key::Comma, "Comma" },
    { Input::Key::Minus, "Minus" },
    { Input::Key::Period, "Period" },
    { Input::Key::Slash, "Slash" },
    { Input::Key::Num_0, "Num_0" },
    { Input::Key::Num_1, "Num_1" },
    { Input::Key::Num_2, "Num_2" },
    { Input::Key::Num_3, "Num_3" },
    { Input::Key::Num_4, "Num_4" },
    { Input::Key::Num_5, "Num_5" },
    { Input::Key::Num_6, "Num_6" },
    { Input::Key::Num_7, "Num_7" },
    { Input::Key::Num_8, "Num_8" },
    { Input::Key::Num_9, "Num_9" },
    { Input::Key::Semicolon, "Semicolon" },
    { Input::Key::Equal, "Equal" },
    { Input::Key::Char_A, "Char_A" },
    { Input::Key::Char_B, "Char_B" },
    { Input::Key::Char_C, "Char_C" },
    { Input::Key::Char_D, "Char_D" },
    { Input::Key::Char_E, "Char_E" },
    { Input::Key::Char_F, "Char_F" },
    { Input::Key::Char_G, "Char_G" },
    { Input::Key::Char_H, "Char_H" },
    { Input::Key::Char_I, "Char_I" },
    { Input::Key::Char_J, "Char_J" },
    { Input::Key::Char_K, "Char_K" },
    { Input::Key::Char_L, "Char_L" },
    { Input::Key::Char_M, "Char_M" },
    { Input::Key::Char_N, "Char_N" },
    { Input::Key::Char_O, "Char_O" },
    { Input::Key::Char_P, "Char_P" },
    { Input::Key::Char_Q, "Char_Q" },
    { Input::Key::Char_R, "Char_R" },
    { Input::Key::Char_S, "Char_S" },
    { Input::Key::Char_T, "Char_T" },
    { Input::Key::Char_U, "Char_U" },
    { Input::Key::Char_V, "Char_V" },
    { Input::Key::Char_W, "Char_W" },
    { Input::Key::Char_X, "Char_X" },
    { Input::Key::Char_Y, "Char_Y" },
    { Input::Key::Char_Z, "Char_Z" },
    { Input::Key::Left_Bracket, "Left_Bracket" },
    { Input::Key::Backslash, "Backslash" },
    { Input::Key::Right_Bracket, "Right_Bracket" },
    { Input::Key::Grave_Accent, "Grave_Accent" },
    { Input::Key::World_1, "World_1" },
    { Input::Key::World_2, "World_2" },
    { Input::Key::Escape, "Escape" },
    { Input::Key::Enter, "Enter" },
    { Input::Key::Tab, "Tab" },
    { Input::Key::Backspace, "Backspace" },
    { Input::Key::Insert, "Insert" },
    { Input::Key::Delete, "Delete" },
    { Input::Key::Right, "Right" },
    { Input::Key::Left, "Left" },
    { Input::Key::Down, "Down" },
    { Input::Key::Up, "Up" },
    { Input::Key::Page_Up, "Page_Up" },
    { Input::Key::Page_Down, "Page_Down" },
    { Input::Key::Home, "Home" },
    { Input::Key::End, "End" },
    { Input::Key::Caps_Lock, "Caps_Lock" },
    { Input::Key::Scroll_Lock, "Scroll_Lock" },
    { Input::Key::Num_Lock, "Num_Lock" },
    { Input::Key::Print_Screen, "Print_Screen" },
    { Input::Key::Pause, "Pause" },
    { Input::Key::F1, "F1" },
    { Input::Key::F2, "F2" },
    { Input::Key::F3, "F3" },
    { Input::Key::F4, "F4" },
    { Input::Key::F5, "F5" },
    { Input::Key::F6, "F6" },
    { Input::Key::F7, "F7" },
    { Input::Key::F8, "F8" },
    { Input::Key::F9, "F9" },
    { Input::Key::F10, "F10" },
    { Input::Key::F11, "F11" },
    { Input::Key::F12, "F12" },
    { Input::Key::F13, "F13" },
    { Input::Key::F14, "F14" },
    { Input::Key::F15, "F15" },
    { Input::Key::F16, "F16" },
    { Input::Key::F17, "F17" },
    { Input::Key::F18, "F18" },
    { Input::Key::F19, "F19" },
    { Input::Key::F20, "F20" },
    { Input::Key::F21, "F21" },
    { Input::Key::F22, "F22" },
    { Input::Key::F23, "F23" },
    { Input::Key::F24, "F24" },
    { Input::Key::F25, "F25" },
    { Input::Key::KeyPad_0, "KeyPad_0" },
    { Input::Key::KeyPad_1, "KeyPad_1" },
    { Input::Key::KeyPad_2, "KeyPad_2" },
    { Input::Key::KeyPad_3, "KeyPad_3" },
    { Input::Key::KeyPad_4, "KeyPad_4" },
    { Input::Key::KeyPad_5, "KeyPad_5" },
    { Input::Key::KeyPad_6, "KeyPad_6" },
    { Input::Key::KeyPad_7, "KeyPad_7" },
    { Input::Key::KeyPad_8, "KeyPad_8" },
    { Input::Key::KeyPad_9, "KeyPad_9" },
    { Input::Key::KeyPad_Decimal, "KeyPad_Decimal" },
    { Input::Key::KeyPad_Divide, "KeyPad_Divide" },
    { Input::Key::KeyPad_Multiply, "KeyPad_Multiply" },
    { Input::Key::KeyPad_Subtract, "KeyPad_Subtract" },
    { Input::Key::KeyPad_Add, "KeyPad_Add" },
    { Input::Key::KeyPad_Enter, "KeyPad_Enter" },
    { Input::Key::KeyPad_Equal, "KeyPad_Equal" },
    { Input::Key::Left_Shift, "Left_Shift" },
    { Input::Key::Left_Control, "Left_Control" },
    { Input::Key::Left_Alt, "Left_Alt" },
    { Input::Key::Left_Super, "Left_Super" },
    { Input::Key::Right_Shift, "Right_Shift" },
    { Input::Key::Right_Control, "Right_Control" },
    { Input::Key::Right_Alt, "Right_Alt" },
    { Input::Key::Right_Super, "Right_Super" },
    { Input::Key::Menu, "Menu" },
    
    { Input::Key::Mouse, "Mouse" },
    { Input::Key::MouseLeft, "MouseLeft" },
    { Input::Key::MouseRight, "MouseRight" },
    { Input::Key::MouseMiddle, "MouseMiddle" },
    { Input::Key::MouseBack, "MouseBack" },
    { Input::Key::MouseForward, "MouseForward" },
    { Input::Key::MouseScrollUp, "MouseScrollUp" },
    { Input::Key::MouseScrollDown, "MouseScrollDown" },
    { Input::Key::MouseScrollLeft, "MouseScrollLeft" },
    { Input::Key::MouseScrollRight, "MouseScrollRight" },
    
    { Input::Key::Touch, "Touch" }
};

}
